<template>
  <main class="content-main njkc-year" role="main">
	<table>
      <tr>
        <th class="njkc-year-sortnum">序號</th>
        <th class="njkc-year-term">學期</th>
        <th class="njkc-year-course">科目名稱</th>
        <th class="njkc-year-igcse">IGCSE</th>
      </tr>
      <tr>
        <td>1</td>
        <td>1</td>
        <td>英語</td>
        <td>V</td>
      </tr>
      <tr>
        <td>2</td>
        <td>1</td>
        <td>中文</td>
        <td>V</td>
      </tr>
      <tr>
        <td>3</td>
        <td>1</td>
        <td>數學</td>
        <td>V</td>
      </tr>
      <tr>
        <td>4</td>
        <td>1</td>
        <td>化學</td>
        <td>V</td>
      </tr>
      <tr>
        <td>5</td>
        <td>1</td>
        <td>物理</td>
        <td>V</td>
      </tr>
      <tr>
        <td>6</td>
        <td>1</td>
        <td>藝術文化</td>
        <td>V</td>
      </tr>
      <tr>
        <td>7</td>
        <td>1</td>
        <td>體育</td>
        <td>V</td>
      </tr>
      <tr>
        <td>8</td>
        <td>1</td>
        <td>世界常識</td>
        <td>V</td>
      </tr>
      <tr>
        <td colspan="3">Subtotal</td>
        <td>8</td>
      </tr>
      <tr>
        <td>1</td>
        <td>2</td>
        <td>英語</td>
        <td>V</td>
      </tr>
      <tr>
        <td>2</td>
        <td>2</td>
        <td>中文</td>
        <td>V</td>
      </tr>
      <tr>
        <td>3</td>
        <td>2</td>
        <td>數學</td>
        <td>V</td>
      </tr>
      <tr>
        <td>4</td>
        <td>2</td>
        <td>化學</td>
        <td>V</td>
      </tr>
      <tr>
        <td>5</td>
        <td>2</td>
        <td>物理</td>
        <td>V</td>
      </tr>
      <tr>
        <td>6</td>
        <td>2</td>
        <td>藝術文化</td>
        <td>V</td>
      </tr>
      <tr>
        <td>7</td>
        <td>2</td>
        <td>體育</td>
        <td>V</td>
      </tr>
      <tr>
        <td>8</td>
        <td>2</td>
        <td>世界常識</td>
        <td>V</td>
      </tr>
      <tr>
        <td colspan="3">Subtotal</td>
        <td>8</td>
      </tr>
      <tr>
        <td colspan="3">Choose for test</td>
        <td>5</td>
      </tr>
    </table>
    <FooterNote/>
  </main>
</template>
<script src="./ten-year.js"></script>
<style src='../structure.css'></style>