let zh_hk = [{
		name:'光榮榜與傑出學生 / 光榮榜',
		path:'/honor/honorary-list',
		data:[
			'等級',
			'大學',
			'學位課程',
			'牛津大學',
			'劍橋大學',
			'伯明罕大學',
			'倫敦大學學院',
			'謝菲爾德大學',
			'帝國理工學院',
			'格拉斯哥大學',
			'倫敦國王學院',
			'華威大學',
			'布裏斯托大學',
			'愛丁堡大學',
			'愛爾蘭皇家外科醫學院',
			'赫瑞瓦特大學',
			'中央蘭開夏大學',
			'紐卡斯爾大學',
			'埃塞克斯大學',
			'香港大學',
			'曼徹斯特大學',
			'薩裏大學',
			'醫學',
			'物理學',
			'土木工程學',
			'經濟學',
			'生物醫學',
			'牙科',
			'社會學',
			'藥劑學',
			'生物醫學科學',
			'電氣工程',
			'精算學',
			'醫學及手術',
			'管理與市場學',
			'國際商務與全球管理',
			'精算學及數學',
			'商業管理',
			'A*A*A',
			'A*A*A*AA',
			'A*AA',
			'A*AB',
			'AAB',
			'A*A*A*A*A',
			'A*AAA',
			'AAA',
			'古典文學',
			'生物化學',
			'工程學',
			'數學',
			'電腦科學',
			'建築學',
			'法學',
			'管理數學',
			'獸醫',
			'2017屆牛津國際公學畢業生',
			'2018屆牛津國際公學畢業生'
		]
	},{
		name:'光榮榜與傑出學生 / 傑出代表',
		path:'/honor/candidates',
		data:[
			'2018年的畢業生中有許多傑出的學生：',
			'Lenny Kwok（5A * A -香港中文大學全球商業）',
			'Karen Poon（5A * -劍橋工程學院）',
			'Angela Lee（4A * A -劍橋醫學）',
			'Avinash Sekar（4A * -劍橋大學經濟學）',
			'Shazril Suhail（4A * -劍橋工程學院）',
			'Jimmy Wong（3A * -劍橋工程學院）'
		]	
	}
]

let en = [{
		name:'Honorary List / Honorary List',
		path:'/honor/honorary-list',
		data:[	
			'Grade',
			'University',
			'Degree Course',
			'University of Oxford'
			'University of Birmingham',
			'University College London (UCL)',
			'University of Sheffield',
			'University of Glasgow',
			'University of Warwick',
			'University of Bristol',
			'University of Edinburgh',
			'University of Newcastle',
			'University of Surrey',
			'Medicine',
			'Civil Engineering',
			'Economics',
			'Physics',
			'Biomedical Sciences',
			'Civil Engineering',
			'Dentistry',
			'Sociology',
			'Pharmacy',
			'Electrical Engineering',
			'Actuarial Science',
			'Medicine and Surgery',
			'Management and Marketing',
			'International Business and Global Management',
			'Actuarial Science and Mathematics',
			'Business Management',
			'University of Cambridge',
			'Imperial College London',
			'Kings College London',
			'Royal College of Surgeons,Ireland',
			'Heriot-Watt University',
			'University of Central Lancashire',
			'University of Essex',
			'University of Hong Kong (HKU)',
			'University of Manchester',
			'A*A*A',
			'A*A*A*AA',
			'A*AA',
			'A*AB',
			'AAB',
			'A*A*A*A*A',
			'A*AAA',
			'AAA',
			'2017 - Oxford International College',
			'2018 - Oxford International College'
	]
	},{
		name:'Honorary List / Outstanding Candidates',
		path:'/honor/candidates',
		data:[
			'Many of the outstanding candidates from class of 2018 are as the following:',
			'Lenny Kwok (5A*A - Global Business in The Chinese University of Hong Kong)',
			'Karen Poon (5A* - Faculty of Engineering in Cambridge University)',
			'Angela Lee (4A*A - Medicine in Cambridge University)',
			'Avinash Sekar (4A* - Economics in Cambridge University)',
			'Shazril Suhail (4A* - Faculty of Engineering in Cambridge University)',
			'Jimmy Wong (3A* - Faculty of Engineering in Cambridge University)'
		]
	}
]

export default{ zh_hk, en }