let zh_hk = 
[
	{
    name: "英國牛津國際公學 / 創辦歷史",
    path: '/njgx/history',
    data: [
        "創辦歷史",
        "英國牛津國際公學在幫助學生成為獨立、積極主劲的學習者並成功入讀英國和世界知名大學上享有盛譽",
        "英國牛津國際公學於2002年由牛津大學的一批學者成立，很快發展為英國名列前茅的牛津風格學院，並歡迎來自世界各地的學生入讀。過去十五年來，從學生到教師員，牛津國際公學創建了一個蓬勃發展的國際化社區",
        "在牛津國際公學，學生由來自牛津的最好的老師教授。我們的老師畢業自牛津大學或世界名校，他們都是各自領域的專家，懂得如何幫助學生獲得最佳表現",
        "馬裏奧,皮特斯博士",
        "牛津國際公學創始人",
        "學士 - 倫敦大學學院|英國第4，世界第15",
        "碩士 - 愛丁堡大學丨英國第6，世界第27",
        "博士 - 牛津大學丨英國第1，世界第1",
        "牛津大學 - 空間物理研究员(1989-1999)",
        "創始人，牛津科學研究(1997)",
        "創始人，牛津國際公學(2003)",
        "創始人，牛津暑假學院(2010)",
        "創始人 ，靑年領導Trust(2012)",
        "創始人 ，Plan8 網球學院，深圳(2013)",
        "金 • 特 拉 爾 女 士",
        "牛津國際公學校長",
        "崇正牛津國際課程項目總負貴人",
        "紐西闌奧塔哥大學",
        "西澳大利亞大學聖喬治學院的住宅地理/地理學導師（擔任多年）",
        "任教於英國海明頓Wycombe Abbey女子學院，並擔任倫敦的獨立中學副院長",
        "擔任牛津國際公學的校友與首席運營官（2011年10月開始）",
        "優思明•薩沃爾女士",
        "首席教育官",
        "2011年度英國科學科導師",
        "2015年度威爾士傑出女性",
        "2015年度諾貝爾傑出教育家獎",
        "英國頂尖醫學院面試小組成員",
        "2016年度TEDx演說家",
        "連續8年A-Level 成績排名記錄保持者",
    	]
  }, {
    name: "英國牛津國際公學 / 教育理念",
    path: '/njgx/objective',
    data: 
    [
        "教育理念",
        "我們相信所有的學生都可以成為未來的專業人士、創新者、領導者或學者。 為了幫助學生在學術和職業生涯中取 得成功，我們認識到：學習需要超越傅統的課堂範圍",
        "在二十一世紀，學生決不能僅僅滿足於聽老師教授如何取得好成績，他們 必須完全投入到自身的學術興趣當中， 參加俱樂部、社團，在他們選擇的學 科競赛中競爭，通過開展新活動走出自己的舒適區,收穫富有洞見的工作經歴，學習如何應對生活中的挑戰",
        "我們學習方法的成效有目共睹。當學 生從學院離開時，他們將成為全面發 展的成人，取得個人成功和專業成就",
        "我們塑造的文化氛圈在於：為自己的成就擔起责任，與具備改善當今世界的使命感",
        "沒有個人品德，學術成就會變得亳無意義。我們充滿熱情地為學生配備各 種互補的技能和能力，這些技能和能力將在他們的人生中為其服務，幫助他們樹立品格和通應能力。希盟學生 能夠通過反思自身經歷、使用這些知識來服務、領導、激勵他人，這就是英國牛津國嫌公學將個人發展纳入其核心裸程的重要原因"
    ]
  }, {
    name: "英國牛津國際公學 / 延伸課程",
    path: '/njgx/programme',
    data: 
    [
        "延伸課程",
        "在英网牛津國際公學，學生將遵循他們個人專屬的全面性戰略規劃道路，最大限度地提高他們進入世界一流大學的機會。“全面性戰略規劃’’課程涉及學生的學術、職業和個人發展。學校的延展課程包括親善大使計劃、 愛丁堡公爵計劃等",
        "親善大使計劃",
        "為學生提供了獨特的機會，通過製作作 品集，參與科學、實驗項目和其他專 業人員的實際工作，讓他們能夠真實 地接觸未來的學位課程", 
        "爱丁堡公爵（DofE )計劃",
        "2018年，牛津國際公學啟動了愛丁堡 公爵（DofE )計劃。該計劃由愛丁堡公爵菲力浦王子在60多年前創立，這 —項世界領先的青年成就獎。包括三 個獎項級別，分別是銅獎、銀獎和金獎。 學生共同努力完成各種挑戰，包括志 願服務、幫助他人、參加體育運動或 舞蹈等文體活動、學習演奏樂器或設 計網站等新技能、甚至參加探險活動",
        "其他活動包括",
        "學術競赛",
        "學生將被強烈鼓勵參加學術競賽，並將得到導師的支持。比賽有助於確保學生在他們想要申請的大學入學名額中獲得一席之地，同時還可以提高他們的寫作技巧和團隊合作能力", 
        "哲學",
        "對於所有學生來說，無論將來他要成為醫療人員、律師還是工程師，哲學都是一個永恆的課題。我們的課堂上充滿了對倫理問題甚至是人類存在問題的爭論。學生們被鼓勵去用他們以前從未想過的方式思考，涉及的主題可能包括：人類是否自由？電腦能否思考？我們如何明辨是非",
        "辩諭",
        "辯論俱樂部對所有學生而言都是一次令人興奮的機會。學生將學會分析案例，並就現實關聯性及頂尖大學非常重視的技能問題進行研究和討論。學生還將參加牛津和劍橋學校的辯論賽",
        "编程",
        "由牛津大學博士生開設的編程課，教授寶貴的技能，無論學生未來選擇哪种職業道路，這門技術都將十分有用", 
        "企業模擬",
        "企業模擬公司計劃為學生提供了獨特的機會，讓他們在團隊中創造、經營自己的企業。他們不僅可以得到有助於大學申請的技能和經驗，而且還可 以賺取他們的成果", 
        "倫敦音樂戲劇藝術學院",
        "倫敦音樂戲劇藝術學院2級口語和聽力技能獎由英格蘭資格及考試監督辦公室和相應的監管機構認可。該獎項 旨在培養英語、口語和肢體語言技能。 學生還將學習如何使聲音語調與相應 的觀眾和講話目的相匹配，並獲得有 效口語交流和參與小組討論所需的知 識和理解内容"
    ]
  }, {
    name: "英國牛津國際公學 / 屢創佳績",
    path: 'njgx/achievement',
    data: [
            "屢創佳績",
            "英國牛津國際公學在獨立學院的中學高级水準考試成績上名列前茅。根據2018年的中學高级水準考試評定結果，牛津國際公學的成结達到AVA為83.5%,當中佔A等级成績有58.2%。去年成績逹到AVA為71%,逭個成績比較起來有著令人藉得鼓舞的進步，讓牛津國嫌學校成為英格藺地區高级水準考試成級最佳的學校之一",
            "牛津國際公學",
            "吉爾福德高中",
            "詹姆斯艾倫女子學校",
            "倫敦",
            "艾德伯格女王學院",
            "約克",
            "西敏公學，西敏",
            "倫敦市",
            "莫德林學院",
            "布萊頓學院",
            "博思學校",
            "劍橋",
            "康科特學院",
            "什羅普郡",
            "倫敦城市女校",
            "崇正牛津國際課程",
            "文科主教老師",
            "貝司國先生",
            "曾在摩根大通集團，法國外贸銀行，富通集團等機構檐任要職",
            "從2010年開始從事教學，持有英文語言教學一等榮辔資格證，任教香港英皇書院同學會小學二校、聖方濟各英文小學、聖若瑟小學等學校","教學時鼓勵學生積極提問，強調幫助學生養成閱讀的好習憤，對提高學生英語能力經驗充足",
             "左韋女士",
            "知名青少年文學作家，獲獎無數之外，多篇作品编入香港内地小學語文及香港小學語文教科書；",
            "有二十多年的豐富教學經験，任職過香港大學SPACE、香港科技大學、香港公開大學、香港城市大學、香港中文大學、香港演藝學院中文課導師；",
            "香港21世紀人文出版社主編，編寫中文教材之餘，多年獲邀擔任香港藝術發展局文學評審員、香港“中文文學獎”、“青年文學獎”評委，香港“文學雙年獎”、“香港會獎”的評審委貝等職。",
            "理科主教老師",
            "鮑勃先生",
            "工程師出身，註冊有五項物理發明専利",
            "曾在中學任教數學、物理及生物，獲得過榮譽教師稱號",
            "會根據學生的英文水準及知識儲備調整 教學節奏、補充教學教材，在保證課堂參與度的同時鍛煉學生的批判性思考能力",
            "黄卓謙先生",
            "香港浸會大學體育及康樂領袖學榮譽學士畢業",
            "香港浸會大學學科講師",
            "花旗銀行健身中心經理",
            "中國香港健美總會/香港棒球總會/香港欖球總會教練",
            "世界常識及藝術科主教老师",
            "謝柏梁教授",
            "北京市高創計晝軍人物國務院政府特殊津貼専家",
            "中國戲曲學院戲文系主任中國文藝評論基地主任",
            "中國戯曲學會常務理事中國戯劇文學學會副會長",
            "張紫伶博士",
            "出身梨園世家，為粤劇宗師白駒榮孫女，名伶白雪梅之女，獲多項音樂國際比赛獎項",
            "英届哥倫比亞大學學士，香港中文大學文化管理碩士，中國藝術研究院（北京）王文章院長博士研究生",
            "港澳非物質文化遗產發展研究會秘書長",
            "中國戯曲學院客席教授，香港演藝學院講師，香港公開大學課程主任",
            "中國傳統文化客席老师",
            "白雪梅女士",
            "梨国世家粤剧名伶",
            "詠春教練 尹教練",
            "尹教練的詠春師承葉問門派",
            "尹教練舉業於美國加州藝術學院與香港理工大學",
            "擔任室内設計專業的大學講師",
            "遨請心理輔導專家",
            "胡美儀女士",
            "香港著名粵曲歌手",
            "心理學專家",
            "崇正牛津國際課程",
            "化學課程",
            "喬纳森貝克特先生",
            "牛津大學化學榮譽碩士畢業",
            "生物課程",
            "佐伊倫迪博士",
            "牛津大學生物化學博士畢業",
            "牛津大學生物化學碩士畢業",
            "物理課程",
            "蒂姆克羅斯額先生",
            "物理碩士畢業",
            "文學碩士畢業",
            "心理學課程",
            "多莉麥克勞林女士",
            "英國超意識心理學家",
            "心理學文憑，英國超意識心理學協會",
            "科學榮譽學士畢業", 
            "數學/統計學課程",
            "茱斯利帕克-柯林斯先生",
            "牛津大學統計學碩士畢業",
            "牛津大學文學榮譽學士畢業",
            "商業學課程",
            "米哈伊爾•拉科夫希克博士",
            "博士畢業",
            "工商管理碩士畢業",
            "科學榮譽碩士畢業",
            "科學榮譽學士畢業",
    ]
  }
]

let en = 
[
	{
    name: "UK Oxford International College / The Establishment",
    path: '/njgx/history',
    data: 
    [
        "Oxford International College has an outstanding reputation for nurturing students to become independent, motivated learners emd successfully gain entry the best British and international universities.",
        "Oxford International College (OIC) was founded in 2002 by a group of experienced scholars from the University of Oxford.It has grown into one of themost successful private colleges in UK, welcoming students from UK and all over the world.Over the past 15 years, the College has created a thrivinginternational community of students and staff",
        "Students are taught by some of Oxford* s finest tutors.Our teaching staff are graduates from the University of Oxford and top universities worldwide and they are experts in their fields.They know what it takes to achieve top grades and how to help students achieve the best performance",

        "BSc - University College London",
        "MSc - Edinburgh",
        "DPhil - Oxford",
        "Oxford University - Researcher in Space Physics",

        "Founder, Oxford Science Studies",

        "Founder, Oxford International College",
        "Founder, Oxford Summer Academy",
        "Founder, Youth Leadership Taist",
        "Founder, Plan8 Tennis Academy.Shenzhen",

        "Principal and Managing Director",

        "Otago University, New Zealand",
        "Residential Qeography/Geography of St.George's College",
        "University of Western Australia Tutor (for many years)",
        "Teaches at Wycombe Abbey of UK, Headington Girls' School and serves as Associate Dean of the Independent Sixth Institute in London",

        "President and Chief Operating Officer of Oxford International College",
        "UK Science Tutor of the Year 2011",
        "Weish Woman of the year 2015",
        "Interview Panelist for 2 Top UK Medical Schools",
        "Claes Nobel Educator of Distinction 2015",
        "TEDx Speaker 2016",
        "Founder of the UK' s Number 1 ranked school for ",
        "A- level results for 8 consecutive years",
        "Ms Yasmin Sarwar",
        "Oxford International College/Chief Education Officer",
    ]
  }, {
    name: "UK Oxford International College / Mission and Objective",
    path: '/njgx/objective',
    data: 
    [
        "Mssion and Objective",
        "We believe all the students can become the professionals, innovators, leaders and scholars.In order to help students achieve success in the academic and career life, we recognize: that learning needs to transcend traditional curriculum range.",
        "Irt the 21st century, students can not only be satisfied with that just follow the teachers and professors how to achieve good results.They must fully participate in their own academic interests, participate in clubs and societies, compete in the discipline competitions they choose, walk out of their comfort zone through newactivities, gain insightful work experience, and learn how to cope with the challenges of life.",
        "The effectiveness of our learning methods is obvious to all.When students leave the college, they will become fully developed adults with personal success and professional achievement.",
        "The cultural atmosphere we create is: responsibility for your achievements and a sense of mission to improve the world today.",
        "Without personal morality, academic achievement will become meaningless.We are passionate about providing students with complementary skills and abilities that will serve them in their lives, helping them to develop character and adaptability.It is hoped that students will be able to serve, lead and motivate others by reflecting on their own experiences and using this knowledge.This is why Oxford International College has incorporated personal development into its core curriculum.",
    ]
  }, {
    name: "UK Oxford International College / Out-reached Programmes",
    path: '/njgx/programme',
    data: 
    [
        "Ouweached Programmes",
        "At Oxford International College in the UK, students will follow their individual and comprehensive strategic planning path to maximize their chances of entering a world-class university. Strategic Global Pathways involves the academic professional emd personal development of students",
        "The out-reached programmes include the Goodwill Ambassador Program, the Duke of Edinburgh Plan and so on",
        "Goodwill Ambassador Programme",
        "It provides students with a unique opportunity to truly reach out to the degree they want to choose in the future through the practical work of producing, performing portfolios, science, experimental projects and other professionals.",
        "Duke of Edinburgh (DofE) program",
        "Students will be strongly encouraged to participate in academic competitions and will be supported by tutors. The competition helps ensure that students get a place in the university places they want to apply for, while also improving their writing skills and teamwork skills.",
        "In 2018, we launched the Duke of Edinburgh (DofE) program at Oxford International College in the UK. The program was founded more than 60 years ago by Prince Philip, the Duke of Edinburgh, the world's leading youth achievement award. It includes three award levels, namely the Bronze, Silver and Gold. Students work together to fulfill a variety of challenges, including volunteering, helping others, participating in sports and dances, learning new skills such as playing instruments or designing websites, and even participating in adventure activities",

        "Other activities include ",
        "Academic Competitions",
        "For all students, philosophy is an eternal subject, whether he wants to be a medical professional, a lawyer or an engineer in the future. Our classroom is full of arguments about ethical issues and even human problems. Students are encouraged to think in ways they have never thought before, and the topics covered may include: Does human has the freedom? Does the computer have the ability of thinking? How do we distinguish between right and wrong",

        "Debate",
        "The debate club is an exciting opportunity for all students. Students will learn to analyze cases and conduct research and discussion on real-world relevance and skills issues that are of great value to top universities. Students will also participate in debates at Oxford and Cambridge schools",

        "The London School of Music and Drama Arts Level 2 Speaking and Listening Skills Awards are recognized by the English Qualifications and Examinations Authority and the appropriate regulatory body. The award aims to develop English, speaking and body language skills. Students will also learn how to match the tone of voice with the appropriate audience and purpose of the speech, and gain the knowledge and understanding needed for effective oral communication and participation in group discussions",

    ]
  }, {
    name: "UK Oxford International College / Achievement over the past",
    path: '/njgx/achievement',
    data: 
    [
        "Achievement over the past",
        "We are proud of the fact that Oxford International College is ranked among the top performers in the independent colleges.",
        "According to the results of the 2018 secondary level examinations, Oxford International College has achieved excellent rankings.The statistical data reached A*/A of 83.5% this year, accounting for 58.2% of the A grade.Last year's achievement reached 71% of A*/A.This result is an encouraging result, and it has become one of the best schools in the UK",
        "TTMS Oxford International Programme",
        "Liberal arts bishop teacher",
        "Mr.BURDETT Scott",
        "Abundant experiences at senior positions in JP Morgan Chase Group, French Foreign Trade Bank, Fortis Group and other institutions",
        "Starts to teach since 2010 with the first-class certificate in English language teaching, teaching schools includes Kings College Old Boys’ Association Primary School No.1, St.Francis of Assisi’ s English Primary School, St.Joseph's Primary School and so on",
        "Scott has sufficient experience in helping students improving their English.He encourages students to ask questions actively during the class and emphasis on help students develop good reading habits",
        "Ms.CHOR Wai",
        "As a well-known youth literature writer, Teacher CHOR has won numerous awards herself and a number of her works have been compiled into the Chinese textbooks in Hong Kong and Mainland China",
        "She has over 20 years of teaching experience, used to work as Chinese Language teacher at the University of Hong Kong SPACE, the Hong Kong University of Science and Technology, the Chinese University of Hong Kong, the City University of Hong Kong, the Open University of Hong Kong, and the Hong Kong Academy for Performing Arts",
        "She is the chief editor at Hong Kong 21st Century Humanities Publishing House, and has been invited to be the judge at Hong Kong Arts Development Council, in Hong Kong Chinese Literature Award, Young Literature Award, and Hong Kong Literature Biennial Award and so on",
        "Science bishop teacher",
        "Mr_ LIVAR Bob ",
        "Bob has registered five physical invention patents as an engineer",
        "He taught mathematics, physics and biology in secondary school and won the honorary teacher title.",
        "He will adjust the pace of teaching and provide supplemental teaching materials according to students' English level and knowledge reserve.He emphasizes on raising students' critical thinking ability while ensuring classroom participation",
        "Mr.Wong Cheuk-him ",
        "Bachelor of Social Sciences in Sport & Recreation Leadership",
        "Lecturer at Hong Kong Baptist University",
        "Fitness Center Manager at Citi Bank",
        "Coach at Hong Kong China Bodybuilding and Fitness Association, Hong Kong Baseball Association Limited, Hong Kong Rugby Union",
        "Prof.Xie Boliang",
        "A leading figure of Beijing's High- level Innovation and Entrepreneurial Talents Supporting Plan, State Council Special Allowance Expert.",
        "Director of the Drama Department of National Academy of Chinese Theatre Arts, Director of the Center for Chinese Literary and Arts Criticism.",
        "Managing Director of the Chinese Opera Society, Vice President of the Chinese Theatre Literature Association.",
        "Dr.Sammi YU",
        "With the family background of opera artists, as the granddaughter of Cantonese opera master PAI JU RONG and the daughter of the famous artist PAI XUE MEI, Sammi won various music awards in international competitions",
        "Bachelor(University of British Columbia),Master in Cultural Management(The Chinese University of Hong Kong), PhD in Theater and ChineseTraditional Opera (Chinese Academy of Arts)",
        "Head of General Secretary, Hong Kong & Macau Intangible Cultural Heritage Research Centre",
        "Visiting Professor at National Academy of Chinese Theatre Arts,lecturer at Hong Kong Academy for Performing Arts, and Curriculum Director at The Open University if Hong Kong",
        "Chinese Culture",
        "MsPaiXueMei ",
        "Wing Chun ",
        "Ms WAN Terry",
        "The Wing Chun training of our coach Ms Wan originates to Master Yip Man",
        "Bachelor of Fine Arts (California College of Arts), Master of Design(HK Polytechnic University)",
        "University Lecturer in Interior Architectural Design",
        "Invite counseling experts",
        "Ms Amy Wu ",
        "Hongkong famous singer of Cantonese Opera",
        "Psychologist",
        "Chemistry",
        "Mr.Jonathan Beckett",
        "Honors Master in Chemistry in University of Oxford",
        "Psychotogy",
        "Ms.Dolly McLaughlin",
        "UK Humanistic Psychology Practitioner",
        "Postgraduate Diploma in Psychology, UK Association of Humanistic Psychology Practitioner",
        "Honors Bachelor of Science",
        "Dr.Zoe Lundy",
        "Biology",
        "Doctor of Philosophy in Biochemistry in University of Oxford",
        "Master in Biochemistry in University of Oxford",
        "Maths / Statistics",
        "Mr.Lesley Parker-Collins",
        "Master of Statistics in University of Oxford",
        "Honors Bachelor of Arts in University of Oxford",
        "Physics",
        "Mr.Tim Croston",
        "Master of Physics",
        "Master of Arts",
        "Business",
        "Dr.Mikhail Rakovshik",
        "PHD",
        "Master of Business Administration",
        "Honors Master of Science",
        "Honors Bachelor of Science",
    ]
  }
] 



export default{ zh_hk, en }