let zh_hk = [{
	name: "崇正牛津國際中學課程 / 質素保證",
	path: '/njkc/assurance',
	data: [
		'質素保證',
		"任課老師由牛津國際公學委派；",
		"授課老師全為母語教學，並在各自領域取得傑出成就。英語授課科目的資深外籍教師，母語為英語，來自英國、美國、加拿大以及其他國家；中文科目授課老師，母語為中文，有二十餘年教學經驗，出版60餘本中文書籍，獲獎無數之餘，也擔任香港各類中文比賽的評審和出版社主編；",
		"教師會定期撰寫學習報告，評估學生的學習進度，報告將提交學校教學委員會，並與家長進行一對一報告，保障學生不斷進步；",
		"秉持著中西融合的教育理念，學校邀請葉問門派的詠春尹教練開設大師班，學習文化色彩濃厚的詠春拳法。尹教練本身也擔任室内設計專業的大學講師，畢業於美國與香港名校。"
	]
}, {
	name: "崇正牛津國際中學課程 / 課程結構",
	path: '/njkc/structure',
	data: [
		'課程結構',
		'1',
		'2',
		'3',
		'4',
		'5',
		'6',
		'7',
		'8',
		'7-8',
		'八年級至十一年級英國舍考',
		'IGCSE與O Level是世界公認的成熟體系，是基於選科的初中教育體系。',
		'十二至十三年級英國高考',
		'英國高中課程，簡稱A level，歷史悠久，認受性廣泛，被幾乎所有英語授課的大學作為招生的入學標準。',
		'報讀大學要求',
		'英國大學',
		'3-4個中學高級水準考試（A-Level）學科英國高校招生服務準備課程',
		'美國大學',
		'3-4個中學高級水準考試（A-Level）學科美國高等院校考試/美國學業能力傾向測験準備課程',
		'香港/新加坡大學',
		'4個中學高級水準考試（A-Level）學科英文授課  ',
		'全球其他國家及地區',
		'4個中學高級水準考試（A-Level）學科母語授課（如需要）',
		'序號',
		'學期',
		'科目名稱',
		'IGCSE',
		'AL',
		'八年級',
		'九年級',
		'十年級',
		'十一年級',
		'十二年級',
		'十二及十三年級',
		'英語',
		'中文',
		'數學',
		'化學',
		'歷史',
		'英語口語',
		'Public Exam',
		'體育',
		'物理',
		'音樂',
		'Subtotal',
		'Choose for test',
		'藝術文化',
		'地理',
		'世界常識',
		'商務',
		'經濟學',
		'藝術設計',
		'個人履歷工作坊',
		'演說技巧',
		'電腦科技',
		'數學延伸',
		'生物學'

	]
}, {
	name: "崇正牛津國際中學課程 / 升學階梯",
	path: '/njkc/articulation',
	data: [
		'升學階梯',
		'碩士學位',
		'3-4年',
		'3年',
		'2年',
		'香港大學',
		'英國或海外大學',
		'中國或亞洲大學',
		'英國大學',
		'銜接第三四年香港學位課程',
		'1年',
		'十二年級 ~ 十三年級（選修文科/理科課程）',
		'英國基礎文憑課程',
		'銜接第三四年香港學位課程',
		'英國高考成績：三科及格達B級或以上，和英文科達C級或上校内成績：二至四科及格',
		'英國會考成績：中文A級，英文C級或以上及三科達D級或以上**+1科達英國高考達（E級）：中大，理大，城大',
		'路徑一',
		'路徑二',
		'十年級至十一年級（選修文科/理科課程）',
		'八年级至九年级（預前英國會考課程）'
	]
}, {
	name: "崇正牛津國際中學課程 / 專修社團",
	path: '/njkc/associations',
	data: [
		'專修社團',
		'表演藝術社團',
		'藝術社團旨在幫助學生發展創造力，通過藝術作品放鬆身心。這是一個發展藝術技能的好機會，同時讓學生有機會從學術學習中抽出時間，享受藝術！歡迎所有想希望通過藝術表演體現自我的學生。',
		'醫學健康社圍',
		'歡迎醫學方向和非醫學方向的學生參加談話和討論，内容關於影響當前醫學的各類問題（包括備受爭議的國民醫療服務體系、醫學倫理，從醫療、經濟學和工程學等不同角度探索醫療保健。這是開發可遷移技能的絕佳機會，如人際交往、溝通技巧、團隊精神和大學面試準備。',
		'金融經濟社團',
		'活動包括以下内容：討論時事、處理統計問題、辯論、博弈論問題、股票挑戰賽、牛津激勵活動、特邀嘉賓演講。',
		'英語精修班',
		'按照不同年級酌情安排。',
		'參與社团另行收費。'
	]
}, {
	name: "崇正牛津國際中學課程 / 交流合作",
	path: '/njkc/cooperation',
	data: [
		'交流合作',
		'香港地區',
		'香港大學、香港科技大學、香港中文大學、香港城市大學、香港理工大學、香港浸會大學、香港嶺南大學、香港樹仁大學、香港演藝學院、香港公開大學',
		'中國地區',
		'北京大學、清華大學、浙江大學、上海交通大學，復旦大學，中山大學，武漢大學、山東大學、北京電影學院、中央戲劇學院、北京體育大學',
		'英國',
		'牛津大學、劍橋大學、帝國理工學院、倫敦大學學院、倫敦政治經濟學院、愛丁堡大學、曼徹斯特大學',
		'美國',
		'加州理工學院、斯坦福大學、哈佛大學、哥倫比亞大學、波士頓大學、茱莉亞音樂學院、伯克利音樂學院、普瑞特藝術學院',
		'加拿大',
		'多倫多大學、英屬哥倫比亞大學、麥基爾大學',
		'澳洲',
		'澳洲國立大學、墨爾本大學、悉尼大學、昆士蘭大學、新南威爾士大學、蒙納士大學、西澳大學、阿德萊德大學',
		'亞洲',
		'新加坡國立大學、南洋理工大學、東京大學、首爾大學'
	]
}]
let en = [{
	name: "TTMS OIC Programme / Quality Assurance",
	path: '/njkc/assurance',
	data: [
		'Quality Assurance',
		"The teacher is recognized by Oxford International College",
		"Teachers are all taught in their mother tongue and have achieved outstanding achievements in their respective fields. Senior foreign teachers in English-language subjects, are native English speaker and come from the United Kingdom, the United States, Canada, and other countries;The Chinese language teacher is native Chinese speaker herself and has more than 20 years of teaching experience. She has published more than 60 Chinese books and won numerous awards. She is also the editor of various Chinese competitions in Hong Kong and Chief Editor from publisher.",
		"Teachers will regularly write study reports to assess the progress of students. The report will be submitted to the school's teaching committee and will be report to parents to ensure students 1 improvement.",
		"Holding the mission of integrate Chinese culture and the Western education, the school invites Ms Terry Wan, the Wing Chun coach originates from Master Yip Man to open a master class for students to learn Wing Chun. Ms Wan is a university lecturer herself in Interior Architectural Design and graduated from top university in USA and HK as well."
	]
}, {
	name: "TTMS OIC Programme / Programme Curriculum",
	path: '/njkc/structure',
	data: [
		'Programme Curriculum',
		'1',
		'2',
		'3',
		'4',
		'5',
		'6',
		'7',
		'8',
		'7-8',
		'Year 8 to Year 11 IGCSE/O Level',
		'IGCSE and O Level are worldwide recognized mature systems in the world and are based on the junior high school education system.',
		'Year 12 to Year 13 AS + A Level',
		'The British General Certificate of Education Advanced Level, referred to as A level, has a long history and wide acceptance, and is accepted as an admission standard by almost all Englishspeaking universities.',
		'Requirements for Higher Education',
		'UK Universities',
		'3-4 A-level subjects UCAS preparation',
		'US Universities',
		'3-4 A-level subjects ACT/SAT preparation',
		'Universities of Hong Kong/Singapore',
		'4 A-Level subjects, English as Teaching Language  ',
		'Rest of the world',
		'4 A-level subjects, plus native language if required',
		'Rank',
		'Semester',
		'Course Title',
		'IGCSE',
		'AL',
		'Year 8',
		'Year 9',
		'Year 10',
		'Year 11',
		'Year 12',
		'Year 12-13',
		'Subtotal',
		"Choose for test",
		'English (First Language/Second Language)',
		'Chinese (First Language)',
		'Mathematics',
		'Chemistry',
		'History',
		'English Oral',
		'Public Exam',
		'Physic Education',
		'Music',
		'Geography',
		'Arts & Culture',
		'Physic',
		'Global Perspectives',
		'Business Studies',
		'Economics',
		'Arts & Design',
		'Presentation Skills',
		'Personal Portfolio Workshop',
		'Biology',
		'Mathematics Additional',
		'Computer Studies'
	]
}, {
	name: "TTMS OIC Programme / Programme Articulation",
	path: '/njkc/articulation',
	data: [
		'Programme Articulation',
		"Master Degree",
		"3-4Y",
		"3Y",
		"2Y",
		"HK University",
		"UK or Oversea University",
		"China or Asian University",
		"UK University",
		"HK Top-up degree",
		"1Y",
		"Y12 ~ Y13 (Streaming Arts / Science curriculum)",
		"UK Foundation Diploma",
		"HK Top-up degree",
		"AL score : Passed 3 subjects] with B grade or above, and English Subject with C or above Some School score : Passed 2-4 subjects",
		"IGCSE score : Chinese at grade A, English at grade C or above and 3 subjects at grade D or above ** +1 AL (E grade): CU, PolyU, CityU",
		"Pathway 1",
		"Pathway 2",
		"Yr10 ~ Yr11 (Streaming Arts / Science curriculum)",
		"Yr8 ~ Yr9 (Preparatory IGCSE curriculum)"
	]
}, {
	name: "TTMS OIC Programme / Professional Associations",
	path: '/njkc/associations',
	data: [
		'Professional Associations',
		'Performing Art Association',
		'This association aims to help students develop creativity and relax through art work. This is a great opportunity to develop artistic skills, while giving students the opportunity to take time out of academic study and enjoy the arts! All students who want to express themselves through artistic performance are welcome.',
		'Medical And Health Association',
		'Students in the medical and non-medical fields are welcome to participate in conversations and discussions on various issues affecting current medicine (including the controversial national medical service system and medical ethics), from different perspectives such as medical, economics and engineering, medical insurance. This is a great opportunity to develop transferable skills such as interpersonal skills, communication skills, teamwork and college interview preparation.',
		'Financial and Economical Association',
		'Activities include the following: discussing current events, dealing with statistical issues, debates, game theory issues, stock challenges, Oxford incentives, and guest speakers.',
		'English Advancement Class',
		"Arrange according to the situation of the students' level.",
		'Participating the associations will have additional charges.'
	]
}, {
	name: "TTMS OIC Programme / Exchange and Cooperation",
	path: '/njkc/cooperation',
	data: [
		'Exchange and Cooperation',
		'Hong Kong',
		'University of Hong Kong, Hong Kong University of Science and Technology, Chinese University of Hong Kong, City University of Hong Kong, Hong Kong Polytechnic University, Hong Kong Baptist University, Lingnan University of Hong Kong, Shuren University of Hong Kong, Hong Kong Academy of Performing Arts, Open University of Hong Kong',
		'China',
		'Peking University, Tsinghua University, Zhejiang University, Shanghai Jiaotong University, Fudan University, Sun Yat-sen University, Wuhan University, Shandong University, Beijing Film Academy, Central Theatre Academy, Beijing Sports University',
		'English',
		'Oxford University, Cambridge University, Imperial College of Technology, London University College, London School of Political Economy, Edinburgh University, Manchester University',
		'America',
		'California Institute of Technology, Stanford University, Harvard University, Columbia University, Boston University, Julia Conservatory of Music, Berkeley Conservatory of Music, Pretty College of Art',
		'Canada',
		'University of Toronto, University of British Columbia, McGill University',
		'Australia',
		'Australian National University, University of Melbourne, University of Sydney, University of Queensland, University of New South Wales, University of Monash, University of Western Australia, University of Adelaide',
		'Asia',
		'National University of Singapore, Nanyang Polytechnic University, Tokyo University, Seoul University'
	]
}]

export default {
	zh_hk,
	en
}