let zh_hk = [{
	name:'入學申請 / 申請資格',
	path:'/rxsq/requirements',
	data:[
	"12歲或以上（合資格入讀8年級至13年級學生）",
	"香港永久性居民",
	"或為合法居港並可在港接受教育人士（如持有香港身份證居民）",
	"或持有其他國籍的人士、在港工作的外籍人士子女等"
	]
},{
	name:'入學申請 / 申請流程',
	path:'/rxsq/procedures',
	data:[
		'通過線上報名收到入學申請表，請填妥入學申請表及下列有關文件親身或郵寄至：',
		'香港九龍長沙灣廣利道11號 香港崇正中學（國際課程入學部）',
		'流程',
		'a. 校方收取入學申請表及核對申請人提交的有關資料後，將於7個工作天内發出面試通告書；',
		'b. 面試分為兩部分：英語面談口試及入學能力測試；',
		'c. 面試後校方計算試卷分數，成績及錄取結果於面試後14個工作天内以書面公佈；',
		'd. 獲取錄的申請人請根據錄取通知書上指定日期繳交按金港幣10,000元*（不設退還），作留位之用；',
		'e. 收費及相關款項必須根據錄取通知書上的指定日期或之前缴付。',
		'有關文件如下：',
		'身份證副本及護照副本',
		'最近三年學歷證明副本',
		' 相關證明檔副本（請參考入學申請表）',
		'報名費繳款證明：接受郵寄劃線支票拾頭為「星光88有限公司」或轉帳到中國銀行（香港）戶口 ： 012-611-0-013044-8',
		'申請人因退學或其他原因不能入學，報名費及按金將不獲退款。',
		'報名時間線',
		'2018',
		'五月至七月',
		'現場報名及面試',
		'十一月中旬',
		'報名開始',
		'2019',
		'七月初',
		' 報名截止（外籍申請人）',
		'七月九日',
		'教育局公佈自行分配學位及統一派位結果',
		'八月三十一日',
		'報名截止（本地申請人）',
		'九月',
		'先修班',
		'九月底',
		'迎新',
		'十月八日',
		'開學日'
	]
},{
	name:'入學申請 / 收費及財務安排',
	path:'/rxsq/fees',
	data:[
		'年級',
		'收費（港幣）',
		'8',
		'148,000',
		'11',
		'158,000',
		'9',
		'12',
		'168,000',
		'10',
		'13',
		'獎學金計劃',
		'$ 1000',
		'崇正牛津獎學金',
		'$ 800',
		'總監嘉賞計劃 ',
		'收費表中的費用已包括：',
		'學校校服一件、運動服一套、學習材料',
		'報名費：港幣300元（不設退還）*',
		'經由學校評選，每學期2位學生可獲得以上獎學金計耋',
		'收費表中的費用不包括：',
		'英國牛津國際公學課程行政費、債券、報名費、捐獻或其他雜費。',
		'學生保險：這是必要的，學生如有其他保險覆盖則可以免除。請注意，校方建議家長自行安排保險，校方不提供保險計劃來支付學費退款。',
		'雅思考試（如有需要）',
		'公開考試費用',
		'額外的一對一課程（例如A-level、IELTS和音樂課程）',
		'學校專修社團及其活動',
		'校外活動和一些可選的課外活動'
	]
}]
let en = [{
	name:'Admission Guideline / Admission Requirements',
	path:'/rxsq/requirements',
	data:[
		"12 years old or above",
	"Hong Kong permanent residents;",
	"or have the right of residence and permission of receiving education in Hong Kong;",
	"or others countries’ residents."
	]
},{
	name:'Admission Guideline / Application Procedures',
	path:'/rxsq/procedures',
	data:[
		'Register online to receive the application form.Please complete the application form and send the following relevant documents in person or by post to: ',
		'Hong Kong Tsung Tsin Middle School (International Programme Admissions Office), No.11 Kwong Lee Road, Cheung Sha Wan, Kowloon, Hong Kong',
		'Process',
		'a. After receiving admissions application, the school will check the relevant documents submitted by the applicant and arrange an interview. The notice of interview will be sent within 7 working days.',
		'b. The interview is divided into two parts: admission test and interview test.',
		'c. The interview results will be announced within 14 working days after the interview.',
		'd. Applicants who have obtained the admissions will pay a deposit of HK$10,000*(non-refundable) for place reservation.',
		'e. The Programme Fee of the 1st semester, the 2nd semester and related payments must be paid by the specified date in the Offer Letter.',
		'The relevant documents',
		'Copy of ID card and passport',
		'Copy of academic certificate in recent three years',
		'Copy of relevant supporting documents (please refer to the application form)',
		'Proof of payment of Registration Fee: Crossed cheque of the registration fee (payable to "Star Light 88 Limited") / registration fee payment receive to Bank of China (HK) account: 012-611-0-013044-8',
		'Registration Fee and Deposit will not be refunded if the applicant is unable to enroll in school.',
		'Timeline',
		'(2018)',
		'MAY To JUL',
		'Walk-in Application & Interview',
		'Middle of NOV',
		'Application Starts',
		'(2019)',
		'Early of JUL',
		'Application Deadline (for non-Local Applicants)',
		'9 JUL',
		'Education Bureau Announces Middle School Offer Results',
		'31 AUG',
		'Application Deadline (for Local Applicants)',
		'SEP',
		'Prep Program',
		'End of SEP',
		'New Student Orientation',
		'8 OCT',
		'Orientation Day'
	]
},{
	name:'Admission Guideline / Fees and Arrangement',
	path:'/rxsq/fees',
	data:[
		'Year',
		'Fees (HK$)',
		'8',
		'148,000',
		'11',
		'158,000',
		'9',
		'12',
		'168,000',
		'10',
		'13',
		'Scholarship Scheme',
		'$ 1000',
		'TTMS-OIC Scholarship',
		'$ 800',
		"Director's Award ",
		'Programme Fees include:',
		'School uniform, sportswear, learning materials',
		'Registration Fee: HK$300(non-refundable)*',
		'2 students per semester can be awarded the above scholarships with certificate from the school.',
		'The following fees are not included in the Programme Fees:',
		'OIC Programme Administrative Fee, Application Fee, Donation Fee, Debenture Fee or other expenses.',
		'Student Insurance is a compulsory unless an alternative cover is provided. Please note that the school does not provide an insurance scheme to cover fee refunds. Parents are encouraged to ',
		'make their own arrangements.',
		'IELTS test (if needed)',
		'>Public examination fee',
		'Additional one-to-one classes (for examples: A-level, IELTS and music lessons)',
		'School Professional Society and its activities',
		'Off-campus activities and some optional extracurricular activities'
	]
}]

export default{ zh_hk, en }