export default{
	getChildAndParentInfo:{
		data:
		[
			{
		      "salutation":"Mr",    
		      "firstName":"Nikey",    
		      "surname":"Welo",    
		      "emailAddress":"Nikey@gmail.com",    
		      "mobileNumber":1343464891,    
		      "attendance":"Yes",    
		      "numberOfAttendees":1,    
		      "firstNameOfGuest":null,    
		      "surnameOfGuest":null,    
		     	"source":"WebSite",
		     	"children":
		     	[
			     	{
				      "firstName":"Nikey_child",	   
				      "surname":"Nikey_child",	    
				      "gender":"F",	   
				      "national":"USA",	    
				      "dataofBirth":"02-12-2012",	    
				      "IntendedEnrollmentYear":"2020-2021",
				      "yearGroupAtEntry":"Year1",
			     	},{
				      "firstName":"Nikey_child",	   
				      "surname":"Nikey_child",	    
				      "gender":"F",	   
				      "national":"USA",	    
				      "dataofBirth":"02-12-2012",	    
				      "IntendedEnrollmentYear":"2020-2021",
				      "yearGroupAtEntry":"Year1",
			     	},{
				      "firstName":"Nikey_child",	   
				      "surname":"Nikey_child",	    
				      "gender":"F",	   
				      "national":"USA",	    
				      "dataofBirth":"02-12-2012",	    
				      "IntendedEnrollmentYear":"2020-2021",
				      "yearGroupAtEntry":"Year1",
			     	}
		     	]
		    	
			},{
		      "salutation":"Mr",    
		      "firstName":"Nikey",    
		      "surname":"Welo",    
		      "emailAddress":"Nikey@gmail.com",    
		      "mobileNumber":1343464891,    
		      "attendance":"Yes",    
		      "numberOfAttendees":1,    
		      "firstNameOfGuest":null,    
		      "surnameOfGuest":null,    
		     	"source":"WebSite",
		     	"children":
		     	[
			     	{
				      "firstName":"Nikey_child",	   
				      "surname":"Nikey_child",	    
				      "gender":"F",	   
				      "national":"USA",	    
				      "dataofBirth":"02-12-2012",	    
				      "IntendedEnrollmentYear":"2020-2021",
				      "yearGroupAtEntry":"Year1",
			     	},{
				      "firstName":"Nikey_child",	   
				      "surname":"Nikey_child",	    
				      "gender":"F",	   
				      "national":"USA",	    
				      "dataofBirth":"02-12-2012",	    
				      "IntendedEnrollmentYear":"2020-2021",
				      "yearGroupAtEntry":"Year1",
			     	},{
				      "firstName":"Nikey_child",	   
				      "surname":"Nikey_child",	    
				      "gender":"F",	   
				      "national":"USA",	    
				      "dataofBirth":"02-12-2012",	    
				      "IntendedEnrollmentYear":"2020-2021",
				      "yearGroupAtEntry":"Year1",
			     	}
		     	]
		    	
			},{
		      "salutation":"Mr",    
		      "firstName":"Nikey",    
		      "surname":"Welo",    
		      "emailAddress":"Nikey@gmail.com",    
		      "mobileNumber":1343464891,    
		      "attendance":"Yes",    
		      "numberOfAttendees":1,    
		      "firstNameOfGuest":null,    
		      "surnameOfGuest":null,    
		     	"source":"WebSite",
		     	"children":
		     	[
			     	{
				      "firstName":"Nikey_child",	   
				      "surname":"Nikey_child",	    
				      "gender":"F",	   
				      "national":"USA",	    
				      "dataofBirth":"02-12-2012",	    
				      "IntendedEnrollmentYear":"2020-2021",
				      "yearGroupAtEntry":"Year1",
			     	},{
				      "firstName":"Nikey_child",	   
				      "surname":"Nikey_child",	    
				      "gender":"F",	   
				      "national":"USA",	    
				      "dataofBirth":"02-12-2012",	    
				      "IntendedEnrollmentYear":"2020-2021",
				      "yearGroupAtEntry":"Year1",
			     	},{
				      "firstName":"Nikey_child",	   
				      "surname":"Nikey_child",	    
				      "gender":"F",	   
				      "national":"USA",	    
				      "dataofBirth":"02-12-2012",	    
				      "IntendedEnrollmentYear":"2020-2021",
				      "yearGroupAtEntry":"Year1",
			     	}
		     	]
		    	
			},
		]
		
	}
}